# frozen_string_literal: true
source "https://rubygems.org"

ruby '~> 2.7.3'
# git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'dotenv', '~> 2.7'
gem 'net-ssh', '~> 6.1'
gem 'net-scp', '~> 3.0'
gem 'net-sftp', '~> 3.0'
gem 'ed25519', '~> 1.2'
gem 'bcrypt_pbkdf', '~> 1.1'
gem 'colorize', '~> 0.8'
gem 'activesupport', '~> 6.1'
gem 'httparty', '~> 0.17'
gem 'nokogiri', '~> 1.11.1'
gem 'highline', '~> 2.0.3'
gem 'pry'
gem 'parallel'
gem 'differ'
gem 'cinch'
gem 'concurrent-ruby', '~> 1.1'
gem 'concurrent-ruby-ext', '~> 1.1'
gem 'json', '~> 2.5'
gem 'terminal-size', '~> 0.0.6'
gem 'tty-cursor', '~> 0.7.1'
gem 'benchmark-ips', '~> 2.8'
gem 'ffi', '~> 1.15'
