# frozen_string_literal: true
source "https://rubygems.org"

# git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'dotenv', '~> 2.7'
gem 'net-ssh', '~> 5.2'
gem 'net-scp', '~> 2.0'
gem 'net-sftp', '~> 2.1'
gem 'colorize', '~> 0.8'
gem 'activesupport', '~> 5.2'
gem 'httparty', '~> 0.17'
gem 'nokogiri'
gem 'highline', '~> 2.0.3'
gem 'pry'
gem 'parallel'
gem 'differ'
gem 'cinch'
gem 'mediainfo', '< 1.0.0'
gem 'concurrent-ruby', '~> 1.1'
gem 'concurrent-ruby-ext', '~> 1.1'
